name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Execute after tests
        run: echo OK
