name: CI

on:
  push:
    branches:
      - master

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Node image
        uses: docker://node:lts-alpine
      - name: Install Dependencies
        run: npm install
